version: "0.1"
user: thaont.spa
key: YDzb9Fmjn75Hk66O7LjtPfFnYaDzXZ3Nln3EqmdAkOtgz0pKFT
testSuites: []
pre: [pip3 install -r requirements.txt --cache-dir CacheDir]
preDirectives:
    commands: [pip3 install -r requirements.txt --cache-dir CacheDir]
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
env:
    TARGET_OS: Windows 10
runson: win
autosplit: true
concurrency: 2
testDiscovery:
    autosubset: true
    command: grep -nri 'class' tests -ir --include=*.py | sed 's/:.*//'
    mode: dynamic
    type: raw
testRunnerCommand: pytest -s  --verbose --html=reports/report.html $test
cacheDirectories:
    - CacheDir
cacheKey: '{{ checksum "requirements.txt" }}'
maxRetries: 1
jobID: fc9098a1-387e-4b21-87b4-fc780c3f0e7a
codeDirectory: Tenerev2
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: false
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
    baseCommand: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
sourcePayload:
    verifySSL: true
collectLocalGitData: true
dynamicAllocation: false
appium: false
